# Generated by Django 5.0.4 on 2024-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="review_days",
            field=models.JSONField(verbose_name="Jours de révision"),
        ),
    ]
