# Generated by Django 5.0.3 on 2024-03-31 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_q", "0017_task_cluster_alter"),
        ("flashcards", "0002_initial"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="topics",
            field=models.ManyToManyField(to="flashcards.topic"),
        ),
        migrations.AddField(
            model_name="schedulemanager",
            name="result_task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_q.task",
            ),
        ),
        migrations.AddField(
            model_name="schedulemanager",
            name="reviewers",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="schedulemanager",
            name="schedule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_q.schedule",
            ),
        ),
    ]
